### ISSUE TITLE
Directory structure in wrapper going too deep

### ISSUE THREAD

**Issue by mdecleir** [spacetelescope/ullyses#51]
I think the wrapper goes 1 layer too deep into the folder structure.
I don't want it to go into subdir (if following the structure below), but with depth=2, it does.
Is it possible that depth should be 1 instead?

```
 # Given a dir structure as follow, setting depth=2 ensure subdir/ will not be read
        # ULLYSES_DATA/
        # |___targ1/
        #     |___subdir/
        #
        depth = 2
        if root[len(indir) :].count(os.sep) >= depth:
            continue
```

**Comment by Rplesha** [comment]
@mdecleir I am looking into this now, and the code appears to be behaving as it should with depth=2, so I'm going to close this issue.

Please feel free to reopen the issue with a reproducible example if you find that even when you are supplying "ULLYSES_DATA" (the top level directory), it continues to find files in "__subdir".
