### ISSUE TITLE
RA & Dec Float vs. String in HLSP Headers

### ISSUE THREAD

**Issue by Rplesha** [spacetelescope/ullyses#56]
If using the ullyses-utils branch: [dr7_updates](https://github.com/spacetelescope/ullyses-utils/tree/dr7_updates), the RA/Dec in the headers of the HLSP become floats instead of strings:
 
     a: hlsp_ullyses_fuse_fuv_av-456_lwrs_dr6_cspec.fits
     b: ULLYSES_HLSP/av456/dr6/hlsp_ullyses_fuse_fuv_av456_lwrs_dr6_cspec.fits
     
     Keyword TARG_DEC has different values:
        (float) a> -72.715444
          (str) b> '-72.7156324722'
     Keyword TARG_RA  has different values:
        (float) a> 17.732292
          (str) b> '17.7323604167'
          
This branch is still a work in progress, so it might be that this is fixed once it is merged, but an easy fix to ensure the RA/Dec in the headers is always in the format we would like is to change the return line to have the data type around it instead. https://github.com/spacetelescope/ullyses/blob/bc3d3f551bf101fb059399d65fd8c2ae3cfedc79/ullyses/wrapper.py#L237

**Comment by jotaylor** [comment]
This was fixed, I believe in 273b7aa
